//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motor_shaft_extension
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Motor_shaft_extension()
        {
            this.Motor_test_data = new HashSet<Motor_test_data>();
        }
    
        public int ID { get; set; }
        public string Series { get; set; }
        public string Config { get; set; }
        public string Desc { get; set; }
        public decimal HeadMin { get; set; }
        public decimal HeadNom { get; set; }
        public decimal HeadMax { get; set; }
        public decimal BaseMin { get; set; }
        public decimal BaseNom { get; set; }
        public decimal BaseMax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Motor_test_data> Motor_test_data { get; set; }
    }
}
