//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Motor()
        {
            this.Motor_test_data = new HashSet<Motor_test_data>();
        }
    
        public int ID { get; set; }
        public string Series { get; set; }
        public string Desc { get; set; }
        public string Model { get; set; }
        public decimal Power { get; set; }
        public decimal Volts { get; set; }
        public decimal Current { get; set; }
        public decimal PhToPhResistance { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Length { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Motor_test_data> Motor_test_data { get; set; }
    }
}
